{{- if .Values.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "nfspv.fullname" . }}-psp
  {{- with .Values.nfspv.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "nfspv.labels" . | nindent 4 }}
spec:
  privileged: {{ .Values.nfspv.privileged }}
  allowPrivilegeEscalation: true
  allowedCapabilities: ['*']
  volumes: ['*']
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  {{- end }}

