{{- if .Values.nfspv.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfspv.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nfspv.annotations }}
  annotations: {{- with .Values.nfspv.annotations }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "nfspv.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nfspv.selectorLabels" . | nindent 8 }}
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        {{- include "nfspv.labels" . | nindent 8  }}
        {{- with .Values.nfspv.podLabels -}}
        {{ toYaml . | nindent 8  }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nfspv.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "nfspv.fullname" . }}
          imagePullPolicy: {{ .Values.nfspv.image.pullPolicy }}
          image: "{{ .Values.nfspv.image.registry }}{{ .Values.nfspv.image.repository }}:{{ default .Chart.AppVersion .Values.nfspv.image.tag }}"
          {{- if .Values.nfspv.resources  }}
          resources:
          {{- toYaml .Values.nfspv.resources | nindent 12 }}
          {{ end }}
          env:
            # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
            # based on this address. This is ignored if empty.
            # This is supported for openebs provisioner version 0.5.2 onwards
            #- name: OPENEBS_IO_K8S_MASTER
            #  value: "http://10.128.0.12:8080"
            # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
            # based on this config. This is ignored if empty.
            # This is supported for openebs provisioner version 0.5.2 onwards
            #- name: OPENEBS_IO_KUBE_CONFIG
            #  value: "/home/ubuntu/.kube/config"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPENEBS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # OPENEBS_SERVICE_ACCOUNT provides the service account of this pod as
            # environment variable
            - name: OPENEBS_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: OPENEBS_IO_ENABLE_ANALYTICS
              value: "{{ .Values.analytics.enabled }}"
            - name: OPENEBS_IO_NFS_SERVER_USE_CLUSTERIP
              value: "{{ .Values.nfsServer.useClusterIP }}"
            - name: OPENEBS_IO_INSTALLER_TYPE
              value: "charts-helm"
          # LEADER_ELECTION_ENABLED is used to enable/disable leader election. By default
          # leader election is enabled.
            - name: LEADER_ELECTION_ENABLED
              value: "{{ .Values.nfspv.enableLeaderElection }}"
          # Process name used for matching is limited to the 15 characters
          # present in the pgrep output.
          # So fullname can't be used here with pgrep (>15 chars).A regular expression
          # that matches the entire command name has to specified.
          # Anchor `^` : matches any string that starts with `provisioner-nfs`
          # `.*`: matches any string that has `provisioner-loc` followed by zero or more char
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test `pgrep -c "^provisioner-nfs.*"` = 1
            initialDelaySeconds: {{ .Values.nfspv.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.nfspv.healthCheck.periodSeconds }}
{{- if .Values.nfspv.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nfspv.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.nfspv.tolerations }}
      tolerations:
{{ toYaml .Values.nfspv.tolerations | indent 8 }}
{{- end }}
{{- if .Values.nfspv.affinity }}
      affinity:
{{ toYaml .Values.nfspv.affinity | indent 8 }}
{{- end }}
{{- end }}
